name: Update GitHub Actions

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # Run every Sunday at midnight

jobs:
  update-actions:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Create temporary GitHub App Token
        id: app
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.HOUSEKEEPING_BOT_APP_ID }}
          private-key: ${{ secrets.HOUSEKEEPING_BOT_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Update GitHub Actions
        uses: alchemaxinc/update-deps/actions@v1
        with:
          token: ${{ steps.app.outputs.token }}
          auto-merge: "true"
          base-branch: "develop"
          prefixes: "actions,golangci,goreleaser,crazy-max,hashicorp"
          file-glob: ".github/**/*.yml"
          branch-prefix: "update-actions"
          pr-title: "chore: update GitHub Actions"
          commit-message: "chore: update github actions"
